//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource.Comic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biografia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Biografia()
        {
            this.Heroe = new HashSet<Heroe>();
        }
    
        public int Id { get; set; }
        public string NombreCompleto { get; set; }
        public string Genero { get; set; }
        public System.DateTime Aparicion { get; set; }
        public string Alias { get; set; }
        public string Editor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Heroe> Heroe { get; set; }
    }
}
