//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource.Comic
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadisticasPoder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EstadisticasPoder()
        {
            this.Heroe = new HashSet<Heroe>();
        }
    
        public int Id { get; set; }
        public int Inteligencia { get; set; }
        public int Fuerza { get; set; }
        public int Velocidad { get; set; }
        public int Durabilidad { get; set; }
        public int Poder { get; set; }
        public int Combate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Heroe> Heroe { get; set; }
    }
}
