//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource.Comic
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Rut { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Password { get; set; }
        public bool Active { get; set; }
        public System.DateTimeOffset Registered { get; set; }
        public int ContactId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Role Role { get; set; }
    }
}
